version: '3'

services:
  # Load Balancer
  haproxy:
    image: haproxy:2.5
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"  # Pour les stats HAProxy
    volumes:
      - ../../config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ../../config/ssl:/etc/ssl/private:ro
    depends_on:
      - web1
      - web2
    networks:
      - coursero-network
    restart: always

  # Serveur Web 1
  web1:
    build:
      context: ../../
      dockerfile: scripts/ha/Dockerfile.web
    volumes:
      - ../../web:/var/www/coursero
      - ../../uploads:/uploads
      - web1_sessions:/var/lib/php/sessions
    environment:
      - SERVER_NAME=web1
    networks:
      - coursero-network
    depends_on:
      - db-master
      - db-slave
    restart: always

  # Serveur Web 2
  web2:
    build:
      context: ../../
      dockerfile: scripts/ha/Dockerfile.web
    volumes:
      - ../../web:/var/www/coursero
      - ../../uploads:/uploads
      - web2_sessions:/var/lib/php/sessions
    environment:
      - SERVER_NAME=web2
    networks:
      - coursero-network
    depends_on:
      - db-master
      - db-slave
    restart: always

  # Serveur de base de données maître
  db-master:
    image: mysql:8.0
    volumes:
      - db_master_data:/var/lib/mysql
      - ../../config/mysql/mysql_master.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=coursero
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - coursero-network
    restart: always

  # Serveur de base de données esclave
  db-slave:
    image: mysql:8.0
    volumes:
      - db_slave_data:/var/lib/mysql
      - ../../config/mysql/mysql_slave.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=coursero
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - coursero-network
    depends_on:
      - db-master
    restart: always

  # Service de traitement de la file d'attente
  queue:
    build:
      context: ../../
      dockerfile: scripts/ha/Dockerfile.queue
    volumes:
      - ../../scripts:/var/www/scripts
      - ../../uploads:/uploads
    depends_on:
      - db-master
      - db-slave
    networks:
      - coursero-network
    restart: always

volumes:
  db_master_data:
  db_slave_data:
  web1_sessions:
  web2_sessions:

networks:
  coursero-network:
    driver: bridge
